# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
host: 0.0.0.0

# Site settings
title:            Full Stack Developer
subtitle:         Ali Nguyen Blog
description:      
language:         "en" # default language of the blog. Language codes: http://www.w3schools.com/tags/ref_language_codes.asp

baseurl:          "" # the subpath of your site, e.g. /blog
permalink:        /blog/:categories/:title
url:              "https://tanngoc93.github.io" # the base hostname & protocol for your site. Have a look at robots.txt as well!
disqus_shortname: "tanngoc93-github-io"
cover:            /assets/mountain-cover.jpg

# Build settings
sass:
  style: compressed
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
include: ['_pages']
exclude: [vendor, "developer-tools"]
plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  ignore:
    envs: [local]
  blanklines: true
  startings: [head, body]